spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: srivatsan
    url: jdbc:mysql://localhost:3306/test
    username: root
  jpa:
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
